### ISSUE TITLE
Reset Password bouncing back to login 

### ISSUE THREAD

**Issue by mullhol** [StatCan/wellBeingCheck#152]
On second entry, I select "forgot your password?" and am taken to the screen to respond to my security question.  When I tap the answer field, it bounces back to the login screen.

**Comment by armonkolaei** [comment]
@AJBouzidi So this issue is not with Forgot password screen.

I believe @Jiandong-Guo  is working on the launch screen where we make several API calls when application is first launched. So if the user quickly navigates to another page while the API call is in progress. After bootstarp is finished the app goes back to the launch screen i believe that is because a state is changed then.

We might have to place a loader on the launch screen so after all api calls are done then we go to the login screen. That should be part of the bootsrtap process. But @Jiandong-Guo can make this change once he is done making all his calls and connecting everything to the API.

**Comment by Jiandong-Guo** [comment]
1) we don't have any api call in launch screen now.
2) I didn't see this issue in android, is it apple specipic ?

**Comment by AJBouzidi** [comment]
@armonkolaei @Jiandong-Guo this is happen on iOS and only the first time you open the app.

**Comment by armonkolaei** [comment]
@AJBouzidi So android is working but not iOS now? They should be the same. Can you please reset iOS and re-download it.
