### ISSUE TITLE
Received too many notification 

### ISSUE THREAD

**Issue by mullhol** [StatCan/wellBeingCheck#280]
I selected 4 notification in my settings menu.  After receiving 2, I modified my preference to 5 notifications per day.  I received a total of 7 by the end of the day.

**Comment by AJBouzidi** [comment]
This is has been fixed and will be in the June 8th release, please reopen it if the functionality not working as expected.

**Comment by mullhol** [comment]
Rachel is currently experiencing this issue. She has a Google Pixel 3 running on Android 10. 

If you have already received your notifications for the day and then go to change the number you want to get, you’ll be sent more notifications. E.g. settings are at 3, 3 have occurred already, respondent changes settings to 2, gets 2 more notifications for a total of 5 in in one day. One day when I tested this it was close to the end of the time frame when I changed the number and I only received one additional notification, not two. Other times it’s been the full number extra.

**Comment by mullhol** [comment]
Patricia is now receiving too many notifications as well.  Here is her information: 

IPhone XR on IOS 13.6.1

I have loaded the new application version last Thursday and set my reminders to 2.  I received 1 reminder not long after and another an hour or so later.  But then I received 3 more notifications. On Friday, I received 7 notifications between 8:38 and 12:42.  I received 8 notifications on Saturday 4 between 12:09 and 12:42 and 4 more between 15:02 and 15:52.  On Sunday I received 4, 2 - 8:28 and 8:42 and 2 more 16:45 and 16:46.  I am not receiving any during the do not disturb hours, but far too many during the awake hours.

**Comment by Jiandong-Guo** [comment]
@AJBouzidi 
One situation many notifications will happen on Android is that
You have received one notification which is beeping and displayed on the notification pane, but user never clicked or removed it. and later on, if there are same notifications comes(Same notifications means they come from same app), all those later notifications will queue on the notification pane and they won't even beep. When user click or remove the stuck notification on the notification pane, all the queued notifications will beeps and pop out at the same time. I think this situation is normal. Today I did the test, in the beginning,I set up notifications:
    time:12:57 ->id:-1845395452
    time:15:26 ->id:1431905178
   ........
   After I get the first notification(I checked the id,it's --1845395452, so far good), I changed the setting, and the new schedule is:
   Time          Id
   14:00        -1623936717
   15:00       1924160458
   16:56       1693971711
  ...........

I didn't touch it until 15:25, I checked my phone notification, found 14:00 one was on the notification pane, 15:00 one is not there, When I removed the 14:00 one on the pane, A new beep and notification was pop out,  I doubt the first time 15:26 one was not deleted, because it's 15:25 now. After I checked the notification Id, The Id is  1924160458, that is for 15:00 one.  So I knew the notification cancellation is working.  The 15:00 one was just stuck by the the 14:00 one and queued there.  if multiple notifications were stuck there, there will be multiple notifications pop ups at the moment when the stuck notification is removed. 
 
I didn't get notifications with same notification Ids under my phone OS setting, if this situation happens I think we have to play with OS settings as posted on the internet.

**Comment by mullhol** [comment]
This issue cannot be tested until the existing tickets for IT concerning not receiving notifications or receiving duplicate notifications have been resolved.

**Comment by mullhol** [comment]
This has not been an issue for Ellen, Holly, or Trish.  Closing the ticket for the time being and will open a new ticket if SM continues to have an issue.

**Comment by mullhol** [comment]
Rachel is currently experiencing this issue on a Pixel 3 on Android 11, app version 1.4.6

Thursday, October 22:
-	12:36: received first notification (36 minutes late)
-	1:21: received second notification at correct time
-	1:22: completed questionnaire, changed to 3 notifications per day, closed app
-	Received three more notifications that evening. Checked too late to see if the first two were on time, but the third was late by an hour.

**Comment by zhuelle** [comment]
@mullhol , I tested the Rachel's scenario on my Android work phone, I received correct number of notifications. Therefore, can you please ask Rachel to test exact scenario again but take the photo of each notification she received that cleared shows the time of notification plus the Notification displayed in the Info button. My concerns are that she confused she received 3 notification in total but she thought she received 3 extra notifications at night that day. Thanks!

**Comment by mullhol** [comment]
Rachel will retest this issue.

**Comment by mullhol** [comment]
Issue has not been replicated. Closing ticket and will reopen if reported again.
