### ISSUE TITLE
Methodology Testing - percentages on first day 

### ISSUE THREAD

**Issue by mullhol** [StatCan/wellBeingCheck#318]
It looks like the percentages for the first day (either the first day of doing the survey or the first day after a settings change) does not always add up to 100%. I’m not sure exactly what his process was but ideally we’d want some sort of proportional re-distribution so that the percentages sum to 100%. 

Could we please have a look at whether or not it's possible to revise this to sum to 100%?

Also, if you could provide me with the logic for this scenario, I will send it to metho to review as well so they can understand how the distribution works.

**Comment by AJBouzidi** [comment]
@mullhol Could we have an example from Methodoloy. ?

**Comment by mullhol** [comment]
@AJBouzidi I've asked Amanda if she can provide an example, but you may need to address the issue she's having accessing the simulator first (noted by Amanda in email this morning)

**Comment by Jiandong-Guo** [comment]
The simulator is not working for IE, you can use modern browser such as Chrome or Edge,
The Bromium seems an anti-virus software, try to play with Bromium's setting and let simulator html running on your local machine.(better download the simulator on your local machine follow as How to use simulator.pdf on github).
In current algorithm, the  percentage sum should be rounded to 100%(It could be 99.99997% or 100.000012345%),    next I will use an example to explain the probability distribution function:
Example:
Step 1) We say we are going to pickup one number from 4 numbers by its probability:
A: probability=30
B: probability=20
C: probability=10
D: probability=15
The total probability=30+20+10+15=75%,
Step 2) proportionally change it to 100%( this step is not necessary from mathematics view, but it is required by the specification document, In our simulator, we use this way to make it total 100%, even not exactly 100% due to the float number type, but it should be 100% after rounding, the math function used to round number is number.toFix(2) which means keep 2 digits of decimal )
A: probability=30/75*100=40
B: probability=20/75*100= 26.66666667
C: probability=10/75*100= 13.33333333
D: probability=15/75*100=20
The total probability=30+20+10+15=100%,
Step 3) create the spinner:
A: 0 to 40, if dice falls to this range choose A
B: 40 to 40+ 26.66666667=66.66666667, if dice falls to this range choose B
C:  66.66666667 to 40+ 26.66666667+13.33333333=80, if dice falls to this range choose C
D: 80 to 80+20=100, if dice falls to this range choose D
Step 4) Create dice:   dice=CreateRandomNum(100);   will create a random number between  0 to 100, So we can check which range the dice falls in the spinner and then pick the number.

Actually from the math view we don’t need to make it to total=100. The process is:  we just omit the step 2, and directly do step 3. The exact steps are:
Step 1A) We say we are going to pickup one number from 4 numbers by its probability:
A: probability=30
B: probability=20
C: probability=10
D: probability=15
The total probability=30+20+10+15=75%,   the total=75 is fine.
Step 2A) create the spinner:
A: 0 to 30, if dice falls to this range choose A
B: 30 to 30+20=50, if dice falls to this range choose B
C:  50 to 30+20+10=60, if dice falls to this range choose C
D: 60 to 30+20+10+15=75, if dice falls to this range choose D
Step 3A) Create dice:   dice=CreateRandomNum(75);   will create a random number between  0 to 75, So we can check which range the dice falls in the spinner and then pick the number.

This is the mathematic function behind the scene.

**Comment by Jiandong-Guo** [comment]
Sorry ,Missing mutiply sign:
A: probability=30/75*100=40
B: probability=20/75*100= 26.66666667
C: probability=10/75*100= 13.33333333
D: probability=15/75*100=20

**Comment by Jiandong-Guo** [comment]
A: probability=30/75 *  100=40
B: probability=20/75 *100= 26.66666667
C: probability=10/75 * 100= 13.33333333
D: probability=15/75 * 100=20

**Comment by mullhol** [comment]
From Amanda: 
The one hour delay makes sense and I was able to verify that this only seems to occur after a user has completed questionnaire A. I was concerned that this happens after each settings change but it did not appear to be the case. And I followed Jiandong’s logic for why the probabilities did not add up to 100%. I’ll go through that again though as I think we can clean up the simulator to make that clearer for future testers.
