### ISSUE TITLE
SAC code page 

### ISSUE THREAD

**Issue by mullhol** [StatCan/wellBeingCheck#324]
The page at the end of the questionnaire with the SAC code - we are currently able to see this for about 1-2 seconds.  Can you confirm if this is an issue with the server we're currently testing on (slow speed), or if additional investigation needs to be done on this?

**Comment by T-T-Nguyen** [comment]
@AJBouzidi @Jiandong-Guo This still appears when linking to Production anonymous portal pre-Beta test.

**Comment by zhuelle** [comment]
@Jiandong-Guo  Could you please comment on this issue as we discussed in our meeting? BTW, I tested and I didn't see the page after clicking the 'Submit' button. I think this is related to the server performance.

**Comment by Jiandong-Guo** [comment]
It is part of the EQ, Cannot be omitted, because this page carry the SAC to mobile app and tell mobile app the EQ is saved and everything is OK, When mobile app detects that page, mobile app will inject a command into this page which will cause EQ refresh this page and trigger this Page to send SAC back to mobile app.  since the SAC is coming from EQ, (not sure how does EQ get this code, maybe get it from CMP),  so if network is slow or EQ web server is slow, users will see that page stay there longer.

**Comment by zhuelle** [comment]
![20210427_112554 (002)](https://user-images.githubusercontent.com/58314003/116269551-53c98180-a74c-11eb-81c6-a721432ec839.jpg)

@Jiandong-Guo @T-T-Nguyen I was able to get a picture of the SAC code page

**Comment by zhuelle** [comment]
@Jiandong-Guo Could you please assigne this ticket back to @T-T-Nguyen so she can proceed to action. Thanks!

**Comment by T-T-Nguyen** [comment]
This remains the same in production. The submission triggers a confirmation popup which appears for a split sec as per meeting on Monday. This is within the EQ? Do you have any solution? @Jiandong-Guo

**Comment by zhuelle** [comment]
@T-T-Nguyen , @Jiandong-Guo already explained in the previous comments that this is not possible to omit.

**Comment by T-T-Nguyen** [comment]
@Jiandong-Guo SMA were made aware of this issue. Ticket can be closed.
