### ISSUE TITLE
Number of notifications popup can be closed by clicking outside the popup

### ISSUE THREAD

**Issue by AJBouzidi** [StatCan/wellBeingCheck#342]
Some popups behave strangely.
Number of notifications popup can be closed by clicking outside the popup, but it immediately reopens before closing.
This behavior is not common to all popup

**Comment by AJBouzidi** [comment]
@Jiandong-Guo  This issue has been done but never merged to production?

**Comment by Jiandong-Guo** [comment]
@AJBouzidi , You may still remember the following story:
In the beginning, when we change something in the setting screen, It will take effect after clicking the back button, the  popup dialog won't  immediately reopens when clicking outside of the dialog, it was exact same as what Forum did.   
one of the important thing when clicking the back button is to trigger a new schedule calculation and update notification schedule.
later client complained if the user changed the setting value, but close the app or left the app alone without clicking the back button, the notification schedule never get updated.  you can search and may find that old ticket created by Holly.
So Saqib changed the flow a little bit and tried to change the modal-less dialog to modal dialog by reopening that popup dialog and forcing the user to click the OK button to close the dialog. so he could implement some logic in the OK button click event.  the source of the problem is the react-native-paper dialog is a modal-less dialog.  What Saqib did is not smooth enough and user can see the flash(reopen action).   

Right now the change is just remove Saqib's re-open function, back to the original solution, if the user change notification number setting without clicking back button, no new schedule will be arranged.  That is the logic in the back end, not just simply hide the dialog by setting the state value to false.

If you want to just simply hide the dialog, I can merge the change next time deploying,  if you want to fix that bug, you have to spend some time to change the modal-less paper dialog into expo modal dialog and implement your logic in OK button click event handler.

**Comment by ForumG-SC** [comment]
It would have been nice to know all of this background information back in June when I was working on this bug. Lack on information and communication resulted in the current resolution which was implemented based on JIRA ticket .

**Comment by Jiandong-Guo** [comment]
changed

**Comment by Jiandong-Guo** [comment]
This one has been changed and will be ready to test in next release
