### ISSUE TITLE
Accessibility issue

### ISSUE THREAD

**Issue by AJBouzidi** [StatCan/wellBeingCheck#354]
URL in FAQ
URL in Terms&Conditions

**Comment by Jiandong-Guo** [comment]
@AJBouzidi 
Accessibility issues related to ParsedText package are:
AboutScreen:
1)faq.c1.q1.a: "faq.c1.q1.a": `Yes. More information can be found on Statistics Canada’s website: **https://www.statcan.gc.ca/wellbeing`,**
2)"faq.c1.q4.a": "The purpose of this pilot study is to better understand the everyday well-being of Canadians by asking in the moment questions about their activities and feelings. For more information about this study, please visit **https://www.statcan.gc.ca/wellbeing",**
3)faq.c2.q4.a: "faq.c2.q4.a": "Yes, Statistics Canada guarantees the confidentiality of your responses under the Statistics Act.\n"+
            "Any research, reports or publications based on this study will use aggregated data only and will not identify you or any individual as being affiliated with this study.\nTo learn more about how Statistics Canada protects your information, visit our **Trust Centre**.",
4)"faq.c2.q6.a": "The Vitali-T-Stat app fully complies with all privacy and security regulations in place to protect Canadians’ information.\n\n"+
            "Vitali-T-Stat uses Statistics Canada’s Electronic Collection Portal to collect your responses. For more information about the security features in place to protect your data, please visit **https://surveys-enquetes.statcan.gc.ca/en/faq/security-securite.html**.",
5)"faq.c6.q1.a":"faq.c6.q1.a":"Please make use of either of the following resources or contact a healthcare professional:\n\n"+"**Mental Health and Wellness**\n\n"

TermOfServiceScreen:
6) "terms_and_conditions_content.privacy.a" :    `Statistics Canada ..........information, visit our **Trust Centre**.\n`,
7) "declinemsg1" :     `Use of this App is strictly in accordance with its Terms and Conditions. Users shall not: decompile, reverse engineer, disassemble or attempt to derive the source code from the App; remove, alter or obscure any proprietary notice from any portion of the App; reproduce, modify, improve, enhance or make derivative works based upon the App; distribute, license, lease, sell, resell, transfer, publicly display, transmit or otherwise exploit the App; link to, mirror or frame any portion of the App for any illegal and unauthorized purpose, and agree to comply with all laws, rules and regulations applicable to their use of the App. \n` ,  **1-877-949-9492**   for more infomations

TOSSettingScreen
8)"terms_and_conditions_content.privacy.a" :    `Statistics Canada ..........information, visit our **Trust Centre**.\n`,

**Comment by T-T-Nguyen** [comment]
Accessibility issues related to ParsedText package are:
AboutScreen:
1)faq.c1.q1.a: "faq.c1.q1.a": Yes. More information can be found on Statistics Canada’s website: **https://www.statcan.gc.ca/wellbeing,**

The link is written already?

2)"faq.c1.q4.a": "The purpose of this pilot study is to better understand the everyday well-being of Canadians by asking in the moment questions about their activities and feelings. For more information about this study, please visit https://www.statcan.gc.ca/wellbeing", 

The link is written already?

3)faq.c2.q4.a: "faq.c2.q4.a": "Yes, Statistics Canada guarantees the confidentiality of your responses under the Statistics Act.\n"+
"Any research, reports or publications based on this study will use aggregated data only and will not identify you or any individual as being affiliated with this study.\nTo learn more about how Statistics Canada protects your information, visit our Trust Centre.",
We can provide the link?

4)"faq.c2.q6.a": "The Vitali-T-Stat app fully complies with all privacy and security regulations in place to protect Canadians’ information.\n\n"+
"Vitali-T-Stat uses Statistics Canada’s Electronic Collection Portal to collect your responses. For more information about the security features in place to protect your data, please visit https://surveys-enquetes.statcan.gc.ca/en/faq/security-securite.html.",


The link is written already?

5)"faq.c6.q1.a":"faq.c6.q1.a":"Please make use of either of the following resources or contact a healthcare professional:\n\n"+"Mental Health and Wellness\n\n"
TermOfServiceScreen:

I was under the impression that Jiandong figured out a way to make it work?

6) "terms_and_conditions_content.privacy.a" : Statistics Canada ..........information, visit our **Trust Centre**.\n,
We can provide the link?

7) "declinemsg1" : Use of this App is strictly in accordance with its Terms and Conditions. Users shall not: decompile, reverse engineer, disassemble or attempt to derive the source code from the App; remove, alter or obscure any proprietary notice from any portion of the App; reproduce, modify, improve, enhance or make derivative works based upon the App; distribute, license, lease, sell, resell, transfer, publicly display, transmit or otherwise exploit the App; link to, mirror or frame any portion of the App for any illegal and unauthorized purpose, and agree to comply with all laws, rules and regulations applicable to their use of the App. \n , 1-877-949-9492 for more infomations
TOSSettingScreen
Where’s the URL?

8)"terms_and_conditions_content.privacy.a" : Statistics Canada ..........information, visit our **Trust Centre**.\n,

Duplicate of 6?

**Comment by Jiandong-Guo** [comment]
#6 is displayed on 2 screens.   all the urls are provided.  the issue is the Talkback just read the whole string, doesn't explicitly read the URL is a button

**Comment by T-T-Nguyen** [comment]
So what is the solution to meet accessibility requirements?

**Comment by T-T-Nguyen** [comment]
@Jiandong-Guo @AJBouzidi 
https://github.com/StatCan/WellbeingCheckUAT/issues/280

**Comment by Jiandong-Guo** [comment]
we are not missing urls, Trust Center is displaying text, inside the link are 
https://www.statcan.gc.ca/eng/trust
https://www.statcan.gc.ca/fra/confiance

**Comment by Jiandong-Guo** [comment]
https://www.statcan.gc.ca/wellBeing  and https://www.statcan.gc.ca/bienetre are not accessible

**Comment by Jiandong-Guo** [comment]
![2](https://user-images.githubusercontent.com/58485300/135632056-093b3185-9194-46db-a89c-0da1bcd7fb70.jpg)
![1](https://user-images.githubusercontent.com/58485300/135632060-dad439b0-6106-43b7-af7e-ad45fede34b4.jpg)

**Comment by AJBouzidi** [comment]
@T-T-Nguyen this is has been done as expected and released. 
If you need to run it by accessibility team?
